### PR TITLE
some modifications

### PR DESCRIPTION
**Pull request by shuhrat**
[Review on Reviewable](https://reviewable.io/reviews/saulis/gemini-teamcity/4)

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/Saulis/gemini-teamcity/pull/4" target="_blank">ReviewNinja

**Comment by Saulis** [comment]
Looks really good! `teamcity-service-messages` seems really handy. If you could fix the few nitpicks I commented, I'll merge this right away, thanks!

---

Review status: all files reviewed, 7 unresolved discussions, some commit checks pending.
Reviewed files:
- lib/plugin.js @ r1
- lib/utils.js @ r1
- package.json @ r1
- test/plugin.js @ r1
- test/utils.js @ r1

---

<sup>**[package.json, line 25 [r1]](https://reviewable.io:443/reviews/saulis/gemini-teamcity/4#-Jpzf-u0LT0bW9QgrWIF)** ([raw file](https://github.com/saulis/gemini-teamcity/blob/6f343ee4b5b6da6dc197ea08bc5713a193ae870a/package.json#L25)):</sup>
I think `mockery` can now be removed from dependencies, since it's no longer used.

---

<sup>**[test/plugin.js, line 11 [r1]](https://reviewable.io:443/reviews/saulis/gemini-teamcity/4#-JpzefIp0LJ8NM-mlWro)** ([raw file](https://github.com/saulis/gemini-teamcity/blob/6f343ee4b5b6da6dc197ea08bc5713a193ae870a/test/plugin.js#L11)):</sup>
Remove trailing spaces please.

---

<sup>**[test/plugin.js, line 29 [r1]](https://reviewable.io:443/reviews/saulis/gemini-teamcity/4#-JpzeWPl4FtYKGWQZxAk)** ([raw file](https://github.com/saulis/gemini-teamcity/blob/6f343ee4b5b6da6dc197ea08bc5713a193ae870a/test/plugin.js#L29)):</sup>
Remove trailing spaces please.

---

<sup>**[test/plugin.js, line 39 [r1]](https://reviewable.io:443/reviews/saulis/gemini-teamcity/4#-JpzeVGrdgGet59N5Hlr)** ([raw file](https://github.com/saulis/gemini-teamcity/blob/6f343ee4b5b6da6dc197ea08bc5713a193ae870a/test/plugin.js#L39)):</sup>
Remove trailing spaces please.

---

<sup>**[test/plugin.js, line 43 [r1]](https://reviewable.io:443/reviews/saulis/gemini-teamcity/4#-JpzeTG5e0Zi2ezNzkxn)** ([raw file](https://github.com/saulis/gemini-teamcity/blob/6f343ee4b5b6da6dc197ea08bc5713a193ae870a/test/plugin.js#L43)):</sup>
Remove trailing spaces please.

---

<sup>**[test/plugin.js, line 120 [r1]](https://reviewable.io:443/reviews/saulis/gemini-teamcity/4#-JpzeO0g_A_cIJqC0jLb)** ([raw file](https://github.com/saulis/gemini-teamcity/blob/6f343ee4b5b6da6dc197ea08bc5713a193ae870a/test/plugin.js#L120)):</sup>
Remove trailing spaces please.

---

<sup>**[test/utils.js, line 24 [r1]](https://reviewable.io:443/reviews/saulis/gemini-teamcity/4#-JpzeGbU66piwBOfS6Ui)** ([raw file](https://github.com/saulis/gemini-teamcity/blob/6f343ee4b5b6da6dc197ea08bc5713a193ae870a/test/utils.js#L24)):</sup>
Remove trailing spaces please.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/saulis/gemini-teamcity/4)

**Comment by shuhrat** [comment]
is it ok now?

**Comment by Saulis** [comment]
Excellent, thank you!

---

Review status: all files reviewed, all discussions resolved, some commit checks pending.
Reviewed files:
- lib/plugin.js @ r2
- lib/utils.js @ r2
- package.json @ r2
- test/plugin.js @ r2
- test/utils.js @ r2

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/saulis/gemini-teamcity/4)

**Pull request merged**
